CREATE TABLE Exams (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	StudentId INT NOT NULL,
	SubjectId INT NOT NULL,
	Grade TINYINT NOT NULL BETWEEN 1 AND 10
);

CREATE TABLE Student (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Firstname CHAR(20) NOT NULL,
	Lastname CHAR(20) NOT NULL,
	DateOfBirth Date NOT NULL,
	Country CHAR(20) NOT NULL,
	City CHAR(20) NOT NULL,
	Address CHAR(20) NOT NULL
);
